#!/bin/bash

quotes=(
    "\"Don't Panic.\""
    "\"Time is an illusion. Lunchtime doubly so.\""
    "\"I love deadlines. I love the whooshing noise they make as they go by.\""
    "\"A learning experience is one of those things that says, 'You know that thing you just did? Don't do that.'\""
    "\"Space is big. You just won't believe how vastly, hugely, mind-bogglingly big it is.\""
    "\"In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.\""
    "\"The ships hung in the sky in much the same way that bricks don't.\""
    "\"I refuse to answer that question on the grounds that I don't know the answer.\""
    "\"I may not have gone where I intended to go, but I think I have ended up where I needed to be.\""
    "\"Human beings, who are almost unique in having the ability to learn from the experience of others, are also remarkable for their apparent disinclination to do so.\""
    "\"Nothing travels faster than the speed of light, with the possible exception of bad news, which obeys its own special laws.\""
    "\"A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.\""
    "\"Let's think the unthinkable, let's do the undoable. Let us prepare to grapple with the ineffable itself, and see if we may not eff it after all.\""
    "\"He felt that his whole life was some kind of dream and he sometimes wondered whose it was and whether they were enjoying it.\""
    "\"For a moment, nothing happened. Then, after a second or so, nothing continued to happen.\""
    "\"If there's anything more important than my ego around, I want it caught and shot now.\""
    "\"We demand rigidly defined areas of doubt and uncertainty!\""
    "\"There is a theory which states that if ever anyone discovers exactly what the Universe is for and why it is here, it will instantly disappear and be replaced by something even more bizarre and inexplicable. There is another theory which states that this has already happened.\""
    "\"The major difference between a thing that might go wrong and a thing that cannot possibly go wrong is that when a thing that cannot possibly go wrong goes wrong it usually turns out to be impossible to get at or repair.\""
    "\"It is a mistake to think you can solve any major problems just with potatoes.\""
    "\"I'd far rather be happy than right any day.\""
    "\"Would it save you a lot of time if I just gave up and went mad now?\""
    "\"You live and learn. At any rate, you live.\""
    "\"Many were increasingly of the opinion that they'd all made a big mistake in coming down from the trees in the first place.\""
    "\"And some said that even the trees had been a bad move, and that no one should ever have left the oceans.\""
    "\"Ford... you're turning into a penguin. Stop it.\""
    "\"My capacity for happiness you could fit into a matchbox without taking out the matches first.\""
    "\"It is an important and popular fact that things are not always what they seem.\""
    "\"If you try and take a cat apart to see how it works, the first thing you have on your hands is a non-working cat.\""
    "\"Anything that happens, happens. Anything that, in happening, causes something else to happen, causes something else to happen.\""
    "\"The fact that we live at the bottom of a deep gravity well, on the surface of a gas covered planet going around a nuclear fireball 90 million miles away and think this to be normal is obviously some indication of how skewed our perspective tends to be.\""
    "\"Isn't it enough to see that a garden is beautiful without having to believe that there are fairies at the bottom of it too?\""
    "\"There is no point in using the word 'impossible' to describe something that has clearly happened.\""
    "\"Anyone who is capable of getting themselves made President should on no account be allowed to do the job.\""
    "\"Life... is like a grapefruit. It's orange and squishy, and has a few pips in it, and some folks have half a one for breakfast.\""
    "\"This planet has - or rather had - a problem, which was this: most of the people on it were unhappy for pretty much of the time.\""
    "\"To summarize the summary of the summary: people are a problem.\""
    "\"All you really need to know for the moment is that the universe is a lot more complicated than you might think, even if you start from a position of thinking it's pretty damn complicated in the first place.\""
    "\"One of the things Ford Prefect had always found hardest to understand about humans was their habit of continually stating and repeating the very very obvious.\""
    "\"The Answer to the Great Question... Of Life, the Universe and Everything... Is... Forty-two.\""
    "\"I don't believe it. Prove it to me and I still won't believe it.\""
    "\"Reality is frequently inaccurate.\""
)

RANDOM_INDEX=$(( RANDOM % ${#quotes[@]} ))

echo "${quotes[$RANDOM_INDEX]}"
