# --- THE BACKGROUND ---
background {
    monitor =
    path = screenshot
    color = rgba(5, 5, 8, 0.9)
    blur_passes = 3
    blur_size = 8
}

# --- THE TERMINAL CLOCK ---
label {
    monitor =
    text = cmd[update:1000] echo "<b>[ $(date +"%H:%M:%S") ]</b>"
    color = rgb(0, 255, 255)
    font_size = 65
    font_family = JetBrainsMono Nerd Font
    position = 0, 120
    halign = center
    valign = center
}

# --- SYSTEM WARNING LABEL ---
label {
    monitor =
    text = Session locked, please enter your password...
    color = rgb(255, 0, 124)
    font_size = 12
    font_family = JetBrainsMono Nerd Font
    position = 0, 30
    halign = center
    valign = center
}

# --- THE HARDENED INPUT FIELD ---
input-field {
    monitor =
    size = 350, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    rounding = 0
    outer_color = rgb(255, 0, 124)
    inner_color = rgb(5, 5, 8)
    font_color = rgb(0, 255, 255)
    font_family = JetBrainsMono Nerd Font
    fade_on_empty = false
    placeholder_text = <span foreground="##00ffff">octanebula@Octavion</span>
    check_color = rgb(0, 255, 255)
    fail_color = rgb(255, 0, 124)
    fail_text = <i>Incorrect password <b>($ATTEMPTS)</b></i>
    position = 0, -30
    halign = center
    valign = center
}

# --- THE DOUGLAS ADAMS TRIBUTE ---
label {
    monitor =
    text = cmd[update:0] ~/.config/hypr/scripts/quote.sh
    color = rgba(0, 255, 255, 0.7)
    font_size = 10
    font_family = JetBrainsMono Nerd Font Italic
    position = 0, -120
    halign = center
    valign = center
}
